export const color = {
    main: "#FC5F00",
    sub: {
        green: "#6cc653",
        yellow: "#ffd13f",
        blue: "#87b3da",
    },
    btnAccent: "#FC5F00",
    btnDefault: "#F1F1F1",
    btnDisable: "rgba(252, 95, 0, 0.4)",
    inputBackground: "#eeeeee88",
    border: "#00000055",
    background: "white",
    textLight: "white",
    textDark: "#555555",
    "page-background": "#FBFCFF",
    "page-dark-text": "#333333",
    "page-bluegrey-text": "#ABA9BC",
    "page-lightgrey-text": "#BABABA",
    "page-grey-text": "#696969",
    "page-color-text": "#FC5F00",
    "page-black-text": "#08252E",
    "header-title-text": "#333439",
    "option-selected-background": "#FFF3EB",
    "option-selected-border": "#FC5F00",
    "option-selected-text": "#CD6A41",
    "option-unselected-background": "#FFFFFF",
    "option-unselected-border": "#BABABA",
    "option-unselected-text": "#BABABA",
    "box-color-background": "#FFF3EB",
    "box-border": "#BABABA",
    "divider-border": "#E8F1FF",
    "input-border": "#EFE3DE",
    "input-focus-border": "#FC5F00",
    "button-accent-background": "#FC5F00",
    "button-accent-disabled-background": "#FFC19B",
    "image-area-background": "#E6E6E6",
};
