const test1 = {
  address: "서울 관악구 관악로 1",
  addressEnglish: "1, Gwanak-ro, Gwanak-gu, Seoul, Korea",
  addressType: "R",
  apartment: "N",
  autoJibunAddress: "서울 관악구 신림동 산 56-1",
  autoJibunAddressEnglish:
    "56-1, mountain, Sillim-dong, Gwanak-gu, Seoul, Gwanak-ro, Gwanak-gu, Seoul, Korea",
  roadname: "관악로",
  roadnameCode: "3120001",
  roadnameEnglish: "Gwanak-ro",
  sido: "서울",
  sidoEnglish: "Seoul",
  sigungu: "관악구",
  sigunguCode: "11620",
  sigunguEnglish: "Gwanak-gu",
  userLanguageType: "K",
  userSelectedType: "R",
  zonecode: "08826",
};

const test2 = {
  address: "경기 남양주시 가운로 2",
  addressEnglish: "2, Gaun-ro, Namyangju-si, Gyeonggi-do, Korea",
  addressType: "R",
  "a apartment": "N",
  autoJibunAddress: "경기 남양주시 다산동 4114-18",
  autoJibunAddressEnglish:
    "4114-18, Dasan-dong, Namyangju-si, Gyeonggi-do, Korea",
  autoRoadAddress: "",
  autoRoadAddressEnglish: "",
  bcode: "4136011200",
  bname: "다산동",
  bname1: "",
  bname1English: "",
  bname2: "다산동",
  bname2English: "Dasan-dong",
  bnameEnglish: "Dasan-dong",
  buildingCode: "4136011000101140018013243",
  buildingName: "원무상가",
  hname: "",
  jibunAddress: "",
  jibunAddressEnglish: "",
  noSelected: "N",
  postcode: "",
  postcode1: "",
  postcode2: "",
  postcodeSeq: "",
  query: "경기도 남양주시 가운로 ",
  roadAddress: "경기 남양주시 가운로 2",
  roadAddressEnglish: "2, Gaun-ro, Namyangju-si, Gyeonggi-do, Korea",
  roadname: "가운로",
  roadnameCode: "3197002",
  roadnameEnglish: "Gaun-ro",
  sido: "경기",
  sidoEnglish: "Gyeonggi-do",
  sigungu: "남양주시",
  sigunguCode: "41360",
  sigunguEnglish: "Namyangju-si",
  userLanguageType: "K",
  userSelectedType: "R",
  zonecode: "12259",
};
